FROM node:22-bookworm-slim

WORKDIR /app

# Install required runtime dependencies directly
RUN npm init -y && \
    npm install --omit=dev \
      express \
      cors \
      body-parser \
      mongoose \
      dotenv \
      morgan \
      image-size \ 
      jsonwebtoken \
      multer \ 
      openai
# Copy your backend source code
COPY . .

CMD ["node", "app.js"]
